blank_issues_enabled: false  
contact_links:
  - name: General Discussion
    url: https://github.com/VoxDroid/Event-Management-System/discussions
    about: For ideas, questions, or feedback, please use the Discussions tab.
  - name: Security Contact
    url: mailto:izeno.contact@gmail.com
    about: For sensitive security issues, please email us directly instead of opening a public issue.